#
# RISC-V system tests
#

TEST_SRC = $(SRC_PATH)/tests/gevico/tcg/riscv64
VPATH += $(TEST_SRC)

LINK_SCRIPT = $(TEST_SRC)/crt/semihost.ld
CRT_SCRIPT = $(TEST_SRC)/crt/crt.S \
             $(TEST_SRC)/crt/memory.c \
             $(TEST_SRC)/crt/console.c
LDFLAGS = -T $(LINK_SCRIPT)
CFLAGS += -I$(TEST_SRC)/crt/ \
          -g -Og -static \
          -march=rv64gcv -mabi=lp64d \
          -mcmodel=medany \
          -Wa,--noexecstack \
          -fvisibility=hidden -nostdlib \
          -Wl,--build-id=none \
          -fno-builtin -mrelax

%: %.c $(CRT_SCRIPT) $(LINK_SCRIPT)
	$(CC) $(CFLAGS) $(CRT_SCRIPT) $(LDFLAGS) $< -o $@

define QEMU_OPTS
-M $(1) -m 2G \
-display none -semihosting \
-serial stdio \
-d int \
-device loader,file=$(2) \
-blockdev driver=file,filename=disk0.img,node-name=flash0 \
-blockdev driver=file,filename=disk1.img,node-name=flash1 \
$(3)
endef

TEST_CASES := board-g233 insn-dma insn-sort insn-crush insn-expand spi-jedec flash-read flash-read-interrupt spi-cs

# Create shared 2M disk images for all tests
disk0.img:
	@echo "Creating shared 2M disk images for tests..."; \
	dd if=/dev/zero of=$@ bs=1M count=2 2>/dev/null;

# Create shared 4M disk images for all tests
disk1.img:
	@echo "Creating shared 4M disk images for tests..."; \
	dd if=/dev/zero of=$@ bs=1M count=4 2>/dev/null;

define case_template
EXTRA_RUNS += run-$(1)
run-$(1): test-$(1) disk0.img disk1.img
	$(call run-test, $$<, $(QEMU) $(call QEMU_OPTS,g233,$$<), $$<, $(TIMEOUT))
gdbstub-$(1): test-$(1) disk0.img disk1.img
	$(call gdbstub-test, $$<, $(QEMU) $(call QEMU_OPTS,g233,$$<, -s -S), $$<, 3600)
endef

$(foreach case,$(TEST_CASES),$(eval $(call case_template,$(case))))

# We don't currently support the multiarch system tests
undefine MULTIARCH_TESTS
